# Объявления
## Объявление по идентификатору

GET http://localhost:4000/offers/648eec37ce55121b171f3d57 HTTP/1.1

###

## Добавление нового объявления

POST http://localhost:4000/offers/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQG1haWwubmV0IiwiaWQiOiI2NDhlZDE2NjNjYzFkNDAwZjZhMjU5MGEiLCJpYXQiOjE2ODczNTY3ODgsImV4cCI6MTY4NzUyOTU4OH0.XL98vqazdSd7s72JhYwcJq0f5XTWIvjwR8uVrGZdtAY

{
  "title": "Роскошный отель в Брюсселе",
  "description": "Просторный дом с прекрасным видом на каналы Амстердама. Идеальное место для семейного отдыха и экскурсий по городу.",
  "publicationDate": "2023-05-12T00:00:00.000Z",
  "city": "Cologne",
  "coordinates": {
    "latitude": 50.938361,
    "longitude": 6.959974
  },
  "previewImage": "cologne-room.jpg",
  "images": [
    "https://paris-apartment1.jpg",
    "https://amsterdam-house1.jpg",
    "https://cologne-room2.jpg",
    "https://brussels-hotel2.jpg",
    "https://brussels-hotel2.jpg",
    "https://hamburg-villa2.jpg"
  ],
  "isPremium": true,
  "isFavorite": true,
  "type": "hotel",
  "rooms": 3,
  "rating": 1,
  "guests": 7,
  "price": 503,
  "amenities": [
    "Washer",
    "Towels",
    "Fridge"
  ],
  "commentCount": 0
}

###

###

## Обновление существующего объявления

PUT http://localhost:4000/offers/648ed4f3a2d4bfc1b3ea2392 HTTP/1.1
Content-Type: application/json

{
  "title": "Роскошная баня в Брюсселе",
  "description": "Просторная баня с прекрасным видом на каналы Амстердама. Идеальное место для семейного отдыха и экскурсий по городу.",
  "publicationDate": "2023-06-19T00:00:00.000Z",
  "coordinates": {
    "latitude": 50.938361,
    "longitude": 6.959974
  },
  "amenities": [
    "Laptop friendly workspace",
    "Washer",
    "Towels",
    "Fridge"
  ]
}

###

## Удаление существующего объявления

DELETE http://localhost:4000/offers/648eec37ce55121b171f3d5c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQG1haWwubmV0IiwiaWQiOiI2NDhlZDE2NjNjYzFkNDAwZjZhMjU5MGEiLCJpYXQiOjE2ODcwODE4MTMsImV4cCI6MTY4NzI1NDYxM30.IXJaOvwzPsgQ5UwW9Roq2cSS7uY66Zo3q57QS7hU08o

###

## Объявления в колличестве указанном в параметре limit

GET http://localhost:4000/offers?limit=60 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQG1haWwubmV0IiwiaWQiOiI2NDhlZDE2NjNjYzFkNDAwZjZhMjU5MGEiLCJpYXQiOjE2ODcyODMwMDgsImV4cCI6MTY4NzQ1NTgwOH0.7HBupuMnuomXjLAFuOZaMJKzRsqCvwcYosG9DYjt3LY

###

## Премиальные объявления
GET http://localhost:4000/offers/premium/Cologne HTTP/1.1

###

## Избранные объявления

GET http://localhost:4000/offers/favorites HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQG1haWwubmV0IiwiaWQiOiI2NDhlZDE2NjNjYzFkNDAwZjZhMjU5MGEiLCJpYXQiOjE2ODcwODE4MTMsImV4cCI6MTY4NzI1NDYxM30.IXJaOvwzPsgQ5UwW9Roq2cSS7uY66Zo3q57QS7hU08o

###

## Добавить объявление в избранное

POST http://localhost:4000/offers/favorites/648ed4f3a2d4bfc1b3ea2392 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQG1haWwubmV0IiwiaWQiOiI2NDhlZDE2NjNjYzFkNDAwZjZhMjU5MGEiLCJpYXQiOjE2ODcwODE4MTMsImV4cCI6MTY4NzI1NDYxM30.IXJaOvwzPsgQ5UwW9Roq2cSS7uY66Zo3q57QS7hU08o

###

## Убрать объявление из избранного

DELETE http://localhost:4000/offers/favorites/648ed4f3a2d4bfc1b3ea2392 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQG1haWwubmV0IiwiaWQiOiI2NDhlZDE2NjNjYzFkNDAwZjZhMjU5MGEiLCJpYXQiOjE2ODcwODE4MTMsImV4cCI6MTY4NzI1NDYxM30.IXJaOvwzPsgQ5UwW9Roq2cSS7uY66Zo3q57QS7hU08o

###
