# Объявления
## Объявление по идентификатору

GET http://localhost:4000/offers/649b29412f09c9a57c164c1f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQGdtYWlsLmNvbSIsImlkIjoiNjQ5YjI5NDEyZjA5YzlhNTdjMTY0YzNhIiwiaWF0IjoxNjg3ODkxNjQ3LCJleHAiOjE2ODgwNjQ0NDd9.PEuKsL9oyiYpPxjeTPe9S-pWiPg0i9oTEmukk7u_Hok

###

## Добавление нового объявления

POST http://localhost:4000/offers/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQGdtYWlsLmNvbSIsImlkIjoiNjQ5OWQ1YmFkNzdhMjE1YzBmNTcwZjg5IiwiaWF0IjoxNjg3ODAzMzMyLCJleHAiOjE2ODc5NzYxMzJ9.qZDdsUOh3aFB7UfMwSviMpgL88IMDqaZbd5MQxyEZO0

{
  "title": "Роскошный отель в Брюсселе",
  "description": "Просторный дом с прекрасным видом на каналы Амстердама. Идеальное место для семейного отдыха и экскурсий по городу.",
  "publicationDate": "2023-05-12T00:00:00.000Z",
  "city": "Paris",
  "coordinates": {
    "latitude": 48.85661,
    "longitude": 2.351499
  },
  "previewImage": "kF2sPYiLb2igLRvte81CN.png",
  "images": [
    "kF2sPYiLb2igLRvte81CN.png",
    "kF2sPYiLb2igLRvte81CN.png",
    "kF2sPYiLb2igLRvte81CN.png",
    "kF2sPYiLb2igLRvte81CN.png",
    "kF2sPYiLb2igLRvte81CN.png",
    "kF2sPYiLb2igLRvte81CN.png"
  ],
  "isPremium": true,
  "isFavorite": true,
  "type": "hotel",
  "rooms": 3,
  "rating": 1,
  "guests": 7,
  "price": 503,
  "amenities": [
    "Washer",
    "Towels",
    "Fridge"
  ],
  "commentCount": 0
}

###

###

## Обновление существующего объявления

PATCH http://localhost:4000/offers/6499d520d77a215c0f570f64 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQGdtYWlsLmNvbSIsImlkIjoiNjQ5OWQ1YmFkNzdhMjE1YzBmNTcwZjg5IiwiaWF0IjoxNjg3ODAzMzMyLCJleHAiOjE2ODc5NzYxMzJ9.qZDdsUOh3aFB7UfMwSviMpgL88IMDqaZbd5MQxyEZO0

{
  "city": "Paris",
  "title": "Роскошная баня в Брюсселе",
  "description": "Просторная баня с прекрасным видом на каналы Амстердама. Идеальное место для семейного отдыха и экскурсий по городу.",
  "publicationDate": "2023-06-19T00:00:00.000Z",
  "coordinates": {
    "latitude": 50.938361,
    "longitude": 6.959974
  },
  "amenities": [
    "Laptop friendly workspace",
    "Washer",
    "Towels",
    "Fridge"
  ]
}

###

## Удаление существующего объявления

DELETE http://localhost:4000/offers/64971e9b4481640f675b8e5f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQGdtYWlsLmNvbSIsImlkIjoiNjQ5NjA1MDI0NDgxNjQwZjY3NWI4ZTFjIiwiaWF0IjoxNjg3NjI1MzQ0LCJleHAiOjE2ODc3OTgxNDR9.0fqm3Sa-BJJfh3mTdXQfB2-ol9HnLyrRWly791ZL6rA

###

## Объявления в колличестве указанном в параметре limit

GET http://localhost:4000/offers?limit=60 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQGdtYWlsLmNvbSIsImlkIjoiNjQ5YjI5NDEyZjA5YzlhNTdjMTY0YzNhIiwiaWF0IjoxNjg3ODkxNjQ3LCJleHAiOjE2ODgwNjQ0NDd9.PEuKsL9oyiYpPxjeTPe9S-pWiPg0i9oTEmukk7u_Hok

###

## Премиальные объявления
GET http://localhost:4000/offers/premium?city=Paris HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQGdtYWlsLmNvbSIsImlkIjoiNjQ5YjI5NDEyZjA5YzlhNTdjMTY0YzNhIiwiaWF0IjoxNjg3ODkxNjQ3LCJleHAiOjE2ODgwNjQ0NDd9.PEuKsL9oyiYpPxjeTPe9S-pWiPg0i9oTEmukk7u_Hok

###

## Избранные объявления

GET http://localhost:4000/offers/favorites HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQGdtYWlsLmNvbSIsImlkIjoiNjQ5YjI5NDEyZjA5YzlhNTdjMTY0YzNhIiwiaWF0IjoxNjg3ODkxNjQ3LCJleHAiOjE2ODgwNjQ0NDd9.PEuKsL9oyiYpPxjeTPe9S-pWiPg0i9oTEmukk7u_Hok

###

## Добавить объявление в избранное

POST http://localhost:4000/offers/favorites/649b29412f09c9a57c164c1f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQGdtYWlsLmNvbSIsImlkIjoiNjQ5YjI5NDEyZjA5YzlhNTdjMTY0YzNhIiwiaWF0IjoxNjg3ODkxNjQ3LCJleHAiOjE2ODgwNjQ0NDd9.PEuKsL9oyiYpPxjeTPe9S-pWiPg0i9oTEmukk7u_Hok

###

## Убрать объявление из избранного

DELETE http://localhost:4000/offers/favorites/649b29412f09c9a57c164c1f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQGdtYWlsLmNvbSIsImlkIjoiNjQ5YjI5NDEyZjA5YzlhNTdjMTY0YzNhIiwiaWF0IjoxNjg3ODkxNjQ3LCJleHAiOjE2ODgwNjQ0NDd9.PEuKsL9oyiYpPxjeTPe9S-pWiPg0i9oTEmukk7u_Hok

###
