# Объявления
## Объявление по идентификатору

GET http://localhost:4000/offers/646e4abea9d42ddd8415bcf8 HTTP/1.1

###

## Добавление нового объявления

POST http://localhost:4000/offers/ HTTP/1.1
Content-Type: application/json

{
  "title": "Роскошный отель в Брюсселе",
  "description": "Просторный дом с прекрасным видом на каналы Амстердама. Идеальное место для семейного отдыха и экскурсий по городу.",
  "publicationDate": "2023-05-14T00:00:00.000Z",
  "city": "Cologne",
  "coordinates": {
    "latitude": 50.938361,
    "longitude": 6.959974
  },
  "previewImage": "cologne-room.jpg",
  "images": [
    "https://paris-apartment1.jpg",
    "https://amsterdam-house1.jpg",
    "https://cologne-room2.jpg",
    "https://brussels-hotel2.jpg",
    "https://hamburg-villa1.jpg"
  ],
  "isPremium": true,
  "isFavorite": true,
  "rating": 3.9,
  "type": "hotel",
  "rooms": 3,
  "guests": 7,
  "price": 503,
  "amenities": [
    "Washer",
    "Towels",
    "Fridge"
  ],
  "authorId": "646e4abea9d42ddd8415bcd2",
  "commentCount": 0
}

###

###

## Обновление существующего объявления

PUT http://localhost:4000/offers/646e4abea9d42ddd8415bcf8 HTTP/1.1
Content-Type: application/json

{
  "title": "Роскошная баня в Брюсселе",
  "description": "Просторная баня с прекрасным видом на каналы Амстердама. Идеальное место для семейного отдыха и экскурсий по городу.",
  "publicationDate": "2023-05-19T00:00:00.000Z",
  "commentCount": 1
}

###

## Обновление существующего объявления

DELETE http://localhost:4000/offers/646e4abea9d42ddd8415bcf8 HTTP/1.1

###

## Объявления в колличестве указанном в параметре limit

GET http://localhost:4000/offers?limit=3 HTTP/1.1

###

## Премиальные объявления в колличестве указанном в параметре limit для города

GET http://localhost:4000/offers/premium/Brussels?limit=2 HTTP/1.1

###

## Избранные объявления в колличестве указанном в параметре limit

GET http://localhost:4000/offers/favorites?limit=3 HTTP/1.1

###

## Добавить объявление в избранное

POST http://localhost:4000/offers/favorites/646e4abea9d42ddd8415bced HTTP/1.1

###

## Убрать объявление из избранного

DELETE http://localhost:4000/offers/favorites/646e4abea9d42ddd8415bced HTTP/1.1

###
