export const AppComponent = {
  RestApplication: Symbol.for('RestApplication'),
  LoggerInterface: Symbol.for('LoggerInterface'),
  ConfigInterface: Symbol.for('ConfigInterface'),
  DatabaseClientInterface: Symbol.for('DatabaseClientInterface'),
  UserServiceInterface: Symbol.for('UserServiceInterface'),
  UserModel: Symbol.for('UserModel'),
  AmenityServiceInterface: Symbol.for('AmenityServiceInterface'),
  AmenityModel: Symbol.for('AmenityModel'),
  CityServiceInterface: Symbol.for('CityServiceInterface'),
  CityModel: Symbol.for('CityModel'),
  TypeOfRentalServiceInterface: Symbol.for('TypeOfRentalServiceInterface'),
  TypeOfRentalModel: Symbol.for('TypeOfRentalModel'),
  TypeOfUserServiceInterface: Symbol.for('TypeOfUserServiceInterface'),
  TypeOfUserModel: Symbol.for('TypeOfUserModel'),
  OfferServiceInterface: Symbol.for('OfferServiceInterface'),
  OfferModel: Symbol.for('OfferModel'),
  CommentServiceInterface: Symbol.for('CommentServiceInterface'),
  CommentModel: Symbol.for('CommentModel'),
  UserController: Symbol.for('UserController'),
} as const;
